apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 16443

# Patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"

# Patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta3
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: 127.0.0.1

nodes:
# The control plane node config
- role: control-plane
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
  - containerPort: 30008
    hostPort: 30008
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

# The worker node configurations
- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
