apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac
  namespace: todoapp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-building
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: rbac
  namespace: todoapp
roleRef:
  kind: Role
  name: rbac
  apiGroup: rbac.authorization.k8s.io