apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: todoapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-secret-role-list
  namespace: todoapp
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["watch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-secret-role-list-binding
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: my-service-account-read
  namespace: todoapp
roleRef:
  kind: Role
  name: my-secret-role-list
  apiGroup: rbac.authorization.k8s.io
