apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-reader
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-reader
  namespace: todoapp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: secrets-reader-binding
 namespace: todoapp
subjects:
- kind: ServiceAccount
  name: secrets-reader
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io