apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-lister
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-lister-role
  namespace: todoapp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]

---

aouVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-lister-binding
  namespace: todoapp
subject:
  - kind: ServiceAccount
    name: secret-lister
    namespace: todoapp
roleRef:
  - kind: Role
    name: secret-lister-role
    apiGroup: rbac.authorization.k8s.io
