kind: ServiceAccount
apiVersion: v1
metadata:
  name: secrets-lister
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todoapp
  name: secret-lister
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-lister-binding
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: secrets-lister
roleRef:
  kind: Role
  name: secret-lister
  apiGroup: rbac.authorization.k8s.io

