apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-lister
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-lister
  namespace: todoapp
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-lister-binging
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: pods-lister
roleRef:
  kind: Role
  name: pods-lister
  apiGroup: rbac.authorization.k8s.io
