apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-pods-sa
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-pods-role
  namespace: todoapp
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-pods-rb
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: list-pods-sa
    namespace: todoapp
roleRef:
  kind: Role
  name: list-pods-role
  apiGroup: rbac.authorization.k8s.io