kind: ServiceAccount
apiVersion: v1
metadata:
 name: secrets-reader
 namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 namespace: todoapp
 name: secrets-reader
rules:
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: secrets-reader-binding
 namespace: todoapp
subjects:
- kind: ServiceAccount # Indicates that the subject is a service account
  name: secrets-reader # This is the name of the service account
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io
