apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-reader
  namespace: todoapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todoapp
  name: secrets-reader
rules:
- apiGroups: [""] # "" indicates the core API group, which includes all core APIs
  resources: ["secrets"] # Indicates the resources that the role can access, in this case, pods
  verbs: ["list", "get"] # Indicates the actions that the role can perform on the resources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-reader-binding
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: secrets-reader 
  namespace: todoapp
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io
