apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-reader
  namespace: todoapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todoapp
  name: secret-list-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods"]
    verbs: ["watch", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-list-role-binding
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: secrets-reader
    namespace: todoapp
roleRef:
  kind: Role
  name: secret-list-role
  apiGroup: rbac.authorization.k8s.io
