# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-reader
  namespace: todoapp

---

# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todoapp
  name: secrets-list-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]

---

# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-list-binding
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: secrets-reader
  namespace: todoapp
roleRef:
  kind: Role
  name: secrets-list-role
  apiGroup: rbac.authorization.k8s.io
