apiVersion: v1
kind: ServiceAccount
metadata:
  name: todoapp-sa
  namespace: todoapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: todoapp-sr
  namespace: todoapp
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todoapp-rb
  namespace: todoapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: todoapp-sr
subjects:
  - kind: ServiceAccount
    name: todoapp-sa
    namespace: todoapp
