---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-reader
  namespace: todoapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-reader
  namespace: todoapp
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-lister-binding
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: secrets-reader
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io
